name: Promote to Production

on:
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout staging branch
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to prod repo
        run: |
          git remote add prod "https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/aarons-hub/prod.git"
          git push prod HEAD:main --force
