name: Promote to Production

on:
  workflow_dispatch: # allows manual trigger from GitHub UI

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout staging code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

      - name: Push to prod repo
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git remote add prod https://x-access-token:${PAT_TOKEN}@github.com/aarons-hub/prod.git
          git push prod HEAD:main --force
